# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/main_dyno.ui'
#
# Created: Sat Apr 25 00:31:55 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DynoMainWindow(object):
    def setupUi(self, DynoMainWindow):
        DynoMainWindow.setObjectName(_fromUtf8("DynoMainWindow"))
        DynoMainWindow.resize(766, 673)
        self.centralwidget = QtGui.QWidget(DynoMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hLayoutInput = QtGui.QHBoxLayout()
        self.hLayoutInput.setObjectName(_fromUtf8("hLayoutInput"))
        self.vLayoutThrottle = QtGui.QVBoxLayout()
        self.vLayoutThrottle.setObjectName(_fromUtf8("vLayoutThrottle"))
        self.Throttle = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Throttle.setFont(font)
        self.Throttle.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle.setMargin(3)
        self.Throttle.setObjectName(_fromUtf8("Throttle"))
        self.vLayoutThrottle.addWidget(self.Throttle)
        self.hLayoutThrottle = QtGui.QHBoxLayout()
        self.hLayoutThrottle.setObjectName(_fromUtf8("hLayoutThrottle"))
        self.hSliderThrottle = QtGui.QSlider(self.centralwidget)
        self.hSliderThrottle.setMaximum(100)
        self.hSliderThrottle.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderThrottle.setObjectName(_fromUtf8("hSliderThrottle"))
        self.hLayoutThrottle.addWidget(self.hSliderThrottle)
        self.spinBoxThrottle = QtGui.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxThrottle.setFont(font)
        self.spinBoxThrottle.setDecimals(0)
        self.spinBoxThrottle.setMaximum(100.0)
        self.spinBoxThrottle.setObjectName(_fromUtf8("spinBoxThrottle"))
        self.hLayoutThrottle.addWidget(self.spinBoxThrottle)
        self.vLayoutThrottle.addLayout(self.hLayoutThrottle)
        self.hLayoutInput.addLayout(self.vLayoutThrottle)
        self.vLayoutLoad = QtGui.QVBoxLayout()
        self.vLayoutLoad.setObjectName(_fromUtf8("vLayoutLoad"))
        self.labelMotor = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelMotor.setFont(font)
        self.labelMotor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMotor.setMargin(3)
        self.labelMotor.setObjectName(_fromUtf8("labelMotor"))
        self.vLayoutLoad.addWidget(self.labelMotor)
        self.hlLayoutLoad = QtGui.QHBoxLayout()
        self.hlLayoutLoad.setObjectName(_fromUtf8("hlLayoutLoad"))
        self.hSliderLoad = QtGui.QSlider(self.centralwidget)
        self.hSliderLoad.setMaximum(100)
        self.hSliderLoad.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderLoad.setObjectName(_fromUtf8("hSliderLoad"))
        self.hlLayoutLoad.addWidget(self.hSliderLoad)
        self.spinBoxLoad = QtGui.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxLoad.setFont(font)
        self.spinBoxLoad.setDecimals(0)
        self.spinBoxLoad.setMaximum(100.0)
        self.spinBoxLoad.setObjectName(_fromUtf8("spinBoxLoad"))
        self.hlLayoutLoad.addWidget(self.spinBoxLoad)
        self.vLayoutLoad.addLayout(self.hlLayoutLoad)
        self.hLayoutInput.addLayout(self.vLayoutLoad)
        self.verticalLayout.addLayout(self.hLayoutInput)
        self.hLayoutOutput_1 = QtGui.QHBoxLayout()
        self.hLayoutOutput_1.setObjectName(_fromUtf8("hLayoutOutput_1"))
        self.vLayoutTorque = QtGui.QVBoxLayout()
        self.vLayoutTorque.setObjectName(_fromUtf8("vLayoutTorque"))
        self.labelTorque = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorque.setFont(font)
        self.labelTorque.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorque.setMargin(3)
        self.labelTorque.setObjectName(_fromUtf8("labelTorque"))
        self.vLayoutTorque.addWidget(self.labelTorque)
        self.hLayoutTorque = QtGui.QHBoxLayout()
        self.hLayoutTorque.setObjectName(_fromUtf8("hLayoutTorque"))
        self.lcdNumberTorque = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTorque.sizePolicy().hasHeightForWidth())
        self.lcdNumberTorque.setSizePolicy(sizePolicy)
        self.lcdNumberTorque.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberTorque.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTorque.setSmallDecimalPoint(True)
        self.lcdNumberTorque.setNumDigits(5)
        self.lcdNumberTorque.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTorque.setProperty("value", 0.0)
        self.lcdNumberTorque.setProperty("intValue", 0)
        self.lcdNumberTorque.setObjectName(_fromUtf8("lcdNumberTorque"))
        self.hLayoutTorque.addWidget(self.lcdNumberTorque)
        self.labelTorqueUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTorqueUnits.sizePolicy().hasHeightForWidth())
        self.labelTorqueUnits.setSizePolicy(sizePolicy)
        self.labelTorqueUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorqueUnits.setFont(font)
        self.labelTorqueUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorqueUnits.setMargin(5)
        self.labelTorqueUnits.setObjectName(_fromUtf8("labelTorqueUnits"))
        self.hLayoutTorque.addWidget(self.labelTorqueUnits)
        self.vLayoutTorque.addLayout(self.hLayoutTorque)
        self.hLayoutOutput_1.addLayout(self.vLayoutTorque)
        self.vLayoutPower = QtGui.QVBoxLayout()
        self.vLayoutPower.setObjectName(_fromUtf8("vLayoutPower"))
        self.labelTach_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach_2.setFont(font)
        self.labelTach_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach_2.setMargin(3)
        self.labelTach_2.setObjectName(_fromUtf8("labelTach_2"))
        self.vLayoutPower.addWidget(self.labelTach_2)
        self.hLayoutPowerLCD = QtGui.QHBoxLayout()
        self.hLayoutPowerLCD.setObjectName(_fromUtf8("hLayoutPowerLCD"))
        self.lcdNumberPower = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberPower.sizePolicy().hasHeightForWidth())
        self.lcdNumberPower.setSizePolicy(sizePolicy)
        self.lcdNumberPower.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberPower.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberPower.setSmallDecimalPoint(True)
        self.lcdNumberPower.setNumDigits(5)
        self.lcdNumberPower.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberPower.setProperty("value", 0.0)
        self.lcdNumberPower.setProperty("intValue", 0)
        self.lcdNumberPower.setObjectName(_fromUtf8("lcdNumberPower"))
        self.hLayoutPowerLCD.addWidget(self.lcdNumberPower)
        self.labelPowerUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPowerUnits.sizePolicy().hasHeightForWidth())
        self.labelPowerUnits.setSizePolicy(sizePolicy)
        self.labelPowerUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPowerUnits.setFont(font)
        self.labelPowerUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPowerUnits.setMargin(5)
        self.labelPowerUnits.setObjectName(_fromUtf8("labelPowerUnits"))
        self.hLayoutPowerLCD.addWidget(self.labelPowerUnits)
        self.vLayoutPower.addLayout(self.hLayoutPowerLCD)
        self.hLayoutOutput_1.addLayout(self.vLayoutPower)
        self.vLayoutTach = QtGui.QVBoxLayout()
        self.vLayoutTach.setObjectName(_fromUtf8("vLayoutTach"))
        self.labelTach = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach.setFont(font)
        self.labelTach.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach.setMargin(3)
        self.labelTach.setObjectName(_fromUtf8("labelTach"))
        self.vLayoutTach.addWidget(self.labelTach)
        self.hLayoutTachLCD = QtGui.QHBoxLayout()
        self.hLayoutTachLCD.setObjectName(_fromUtf8("hLayoutTachLCD"))
        self.lcdNumberTach = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTach.sizePolicy().hasHeightForWidth())
        self.lcdNumberTach.setSizePolicy(sizePolicy)
        self.lcdNumberTach.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberTach.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTach.setSmallDecimalPoint(True)
        self.lcdNumberTach.setNumDigits(5)
        self.lcdNumberTach.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTach.setProperty("value", 0.0)
        self.lcdNumberTach.setProperty("intValue", 0)
        self.lcdNumberTach.setObjectName(_fromUtf8("lcdNumberTach"))
        self.hLayoutTachLCD.addWidget(self.lcdNumberTach)
        self.labelTachUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTachUnits.sizePolicy().hasHeightForWidth())
        self.labelTachUnits.setSizePolicy(sizePolicy)
        self.labelTachUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachUnits.setFont(font)
        self.labelTachUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachUnits.setMargin(5)
        self.labelTachUnits.setObjectName(_fromUtf8("labelTachUnits"))
        self.hLayoutTachLCD.addWidget(self.labelTachUnits)
        self.vLayoutTach.addLayout(self.hLayoutTachLCD)
        self.hLayoutOutput_1.addLayout(self.vLayoutTach)
        self.vLayoutTachCAN = QtGui.QVBoxLayout()
        self.vLayoutTachCAN.setObjectName(_fromUtf8("vLayoutTachCAN"))
        self.labelTachCAN = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachCAN.setFont(font)
        self.labelTachCAN.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachCAN.setMargin(3)
        self.labelTachCAN.setObjectName(_fromUtf8("labelTachCAN"))
        self.vLayoutTachCAN.addWidget(self.labelTachCAN)
        self.hLayoutTachCAN = QtGui.QHBoxLayout()
        self.hLayoutTachCAN.setObjectName(_fromUtf8("hLayoutTachCAN"))
        self.lcdNumberTachCAN = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTachCAN.sizePolicy().hasHeightForWidth())
        self.lcdNumberTachCAN.setSizePolicy(sizePolicy)
        self.lcdNumberTachCAN.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberTachCAN.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTachCAN.setSmallDecimalPoint(True)
        self.lcdNumberTachCAN.setNumDigits(5)
        self.lcdNumberTachCAN.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTachCAN.setProperty("value", 0.0)
        self.lcdNumberTachCAN.setProperty("intValue", 0)
        self.lcdNumberTachCAN.setObjectName(_fromUtf8("lcdNumberTachCAN"))
        self.hLayoutTachCAN.addWidget(self.lcdNumberTachCAN)
        self.labelTachCANUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTachCANUnits.sizePolicy().hasHeightForWidth())
        self.labelTachCANUnits.setSizePolicy(sizePolicy)
        self.labelTachCANUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachCANUnits.setFont(font)
        self.labelTachCANUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachCANUnits.setMargin(5)
        self.labelTachCANUnits.setObjectName(_fromUtf8("labelTachCANUnits"))
        self.hLayoutTachCAN.addWidget(self.labelTachCANUnits)
        self.vLayoutTachCAN.addLayout(self.hLayoutTachCAN)
        self.hLayoutOutput_1.addLayout(self.vLayoutTachCAN)
        self.verticalLayout.addLayout(self.hLayoutOutput_1)
        self.hLayoutOutput_2 = QtGui.QHBoxLayout()
        self.hLayoutOutput_2.setObjectName(_fromUtf8("hLayoutOutput_2"))
        self.vLayoutCurrent = QtGui.QVBoxLayout()
        self.vLayoutCurrent.setObjectName(_fromUtf8("vLayoutCurrent"))
        self.labelCurrent = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrent.setFont(font)
        self.labelCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrent.setMargin(3)
        self.labelCurrent.setObjectName(_fromUtf8("labelCurrent"))
        self.vLayoutCurrent.addWidget(self.labelCurrent)
        self.hLayoutCurrentLCD = QtGui.QHBoxLayout()
        self.hLayoutCurrentLCD.setObjectName(_fromUtf8("hLayoutCurrentLCD"))
        self.lcdNumberCurrent = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberCurrent.sizePolicy().hasHeightForWidth())
        self.lcdNumberCurrent.setSizePolicy(sizePolicy)
        self.lcdNumberCurrent.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberCurrent.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberCurrent.setSmallDecimalPoint(True)
        self.lcdNumberCurrent.setNumDigits(5)
        self.lcdNumberCurrent.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberCurrent.setProperty("value", 0.0)
        self.lcdNumberCurrent.setProperty("intValue", 0)
        self.lcdNumberCurrent.setObjectName(_fromUtf8("lcdNumberCurrent"))
        self.hLayoutCurrentLCD.addWidget(self.lcdNumberCurrent)
        self.labelCurrentUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentUnits.sizePolicy().hasHeightForWidth())
        self.labelCurrentUnits.setSizePolicy(sizePolicy)
        self.labelCurrentUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentUnits.setFont(font)
        self.labelCurrentUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentUnits.setMargin(5)
        self.labelCurrentUnits.setObjectName(_fromUtf8("labelCurrentUnits"))
        self.hLayoutCurrentLCD.addWidget(self.labelCurrentUnits)
        self.vLayoutCurrent.addLayout(self.hLayoutCurrentLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutCurrent)
        self.vLayoutVoltage = QtGui.QVBoxLayout()
        self.vLayoutVoltage.setObjectName(_fromUtf8("vLayoutVoltage"))
        self.labelTach_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach_3.setFont(font)
        self.labelTach_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach_3.setMargin(3)
        self.labelTach_3.setObjectName(_fromUtf8("labelTach_3"))
        self.vLayoutVoltage.addWidget(self.labelTach_3)
        self.hLayoutVoltageLCD = QtGui.QHBoxLayout()
        self.hLayoutVoltageLCD.setObjectName(_fromUtf8("hLayoutVoltageLCD"))
        self.lcdNumberVoltage = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberVoltage.sizePolicy().hasHeightForWidth())
        self.lcdNumberVoltage.setSizePolicy(sizePolicy)
        self.lcdNumberVoltage.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberVoltage.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberVoltage.setSmallDecimalPoint(True)
        self.lcdNumberVoltage.setNumDigits(5)
        self.lcdNumberVoltage.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberVoltage.setProperty("value", 0.0)
        self.lcdNumberVoltage.setProperty("intValue", 0)
        self.lcdNumberVoltage.setObjectName(_fromUtf8("lcdNumberVoltage"))
        self.hLayoutVoltageLCD.addWidget(self.lcdNumberVoltage)
        self.labelVoltageUnits_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVoltageUnits_2.sizePolicy().hasHeightForWidth())
        self.labelVoltageUnits_2.setSizePolicy(sizePolicy)
        self.labelVoltageUnits_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVoltageUnits_2.setFont(font)
        self.labelVoltageUnits_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVoltageUnits_2.setMargin(5)
        self.labelVoltageUnits_2.setObjectName(_fromUtf8("labelVoltageUnits_2"))
        self.hLayoutVoltageLCD.addWidget(self.labelVoltageUnits_2)
        self.vLayoutVoltage.addLayout(self.hLayoutVoltageLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutVoltage)
        self.vLayoutMCTemp = QtGui.QVBoxLayout()
        self.vLayoutMCTemp.setObjectName(_fromUtf8("vLayoutMCTemp"))
        self.labelMCTemp = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMCTemp.setFont(font)
        self.labelMCTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMCTemp.setMargin(3)
        self.labelMCTemp.setObjectName(_fromUtf8("labelMCTemp"))
        self.vLayoutMCTemp.addWidget(self.labelMCTemp)
        self.hLayoutMCTempLCD = QtGui.QHBoxLayout()
        self.hLayoutMCTempLCD.setObjectName(_fromUtf8("hLayoutMCTempLCD"))
        self.lcdNumberMCTemp = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberMCTemp.sizePolicy().hasHeightForWidth())
        self.lcdNumberMCTemp.setSizePolicy(sizePolicy)
        self.lcdNumberMCTemp.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberMCTemp.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberMCTemp.setSmallDecimalPoint(True)
        self.lcdNumberMCTemp.setNumDigits(5)
        self.lcdNumberMCTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberMCTemp.setProperty("value", 0.0)
        self.lcdNumberMCTemp.setProperty("intValue", 0)
        self.lcdNumberMCTemp.setObjectName(_fromUtf8("lcdNumberMCTemp"))
        self.hLayoutMCTempLCD.addWidget(self.lcdNumberMCTemp)
        self.labelMCTempUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMCTempUnits.sizePolicy().hasHeightForWidth())
        self.labelMCTempUnits.setSizePolicy(sizePolicy)
        self.labelMCTempUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMCTempUnits.setFont(font)
        self.labelMCTempUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMCTempUnits.setMargin(5)
        self.labelMCTempUnits.setObjectName(_fromUtf8("labelMCTempUnits"))
        self.hLayoutMCTempLCD.addWidget(self.labelMCTempUnits)
        self.vLayoutMCTemp.addLayout(self.hLayoutMCTempLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutMCTemp)
        self.vLayoutMTemp = QtGui.QVBoxLayout()
        self.vLayoutMTemp.setObjectName(_fromUtf8("vLayoutMTemp"))
        self.labelMTemp = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMTemp.setFont(font)
        self.labelMTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMTemp.setMargin(3)
        self.labelMTemp.setObjectName(_fromUtf8("labelMTemp"))
        self.vLayoutMTemp.addWidget(self.labelMTemp)
        self.hLayoutMTemp = QtGui.QHBoxLayout()
        self.hLayoutMTemp.setObjectName(_fromUtf8("hLayoutMTemp"))
        self.lcdNumberMTemp = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberMTemp.sizePolicy().hasHeightForWidth())
        self.lcdNumberMTemp.setSizePolicy(sizePolicy)
        self.lcdNumberMTemp.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumberMTemp.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberMTemp.setSmallDecimalPoint(True)
        self.lcdNumberMTemp.setNumDigits(5)
        self.lcdNumberMTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberMTemp.setProperty("value", 0.0)
        self.lcdNumberMTemp.setProperty("intValue", 0)
        self.lcdNumberMTemp.setObjectName(_fromUtf8("lcdNumberMTemp"))
        self.hLayoutMTemp.addWidget(self.lcdNumberMTemp)
        self.labelMTempUnits = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMTempUnits.sizePolicy().hasHeightForWidth())
        self.labelMTempUnits.setSizePolicy(sizePolicy)
        self.labelMTempUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMTempUnits.setFont(font)
        self.labelMTempUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMTempUnits.setMargin(5)
        self.labelMTempUnits.setObjectName(_fromUtf8("labelMTempUnits"))
        self.hLayoutMTemp.addWidget(self.labelMTempUnits)
        self.vLayoutMTemp.addLayout(self.hLayoutMTemp)
        self.hLayoutOutput_2.addLayout(self.vLayoutMTemp)
        self.verticalLayout.addLayout(self.hLayoutOutput_2)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 250))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.hLayoutDataButtons = QtGui.QHBoxLayout()
        self.hLayoutDataButtons.setObjectName(_fromUtf8("hLayoutDataButtons"))
        self.buttonPauseData = QtGui.QPushButton(self.centralwidget)
        self.buttonPauseData.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPauseData.setFont(font)
        self.buttonPauseData.setCheckable(True)
        self.buttonPauseData.setDefault(False)
        self.buttonPauseData.setFlat(False)
        self.buttonPauseData.setObjectName(_fromUtf8("buttonPauseData"))
        self.hLayoutDataButtons.addWidget(self.buttonPauseData)
        self.buttonClearData = QtGui.QPushButton(self.centralwidget)
        self.buttonClearData.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonClearData.setFont(font)
        self.buttonClearData.setDefault(False)
        self.buttonClearData.setFlat(False)
        self.buttonClearData.setObjectName(_fromUtf8("buttonClearData"))
        self.hLayoutDataButtons.addWidget(self.buttonClearData)
        self.verticalLayout.addLayout(self.hLayoutDataButtons)
        self.buttonEmergency = QtGui.QPushButton(self.centralwidget)
        self.buttonEmergency.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEmergency.setFont(font)
        self.buttonEmergency.setStyleSheet(_fromUtf8("background-color: red;"))
        self.buttonEmergency.setDefault(False)
        self.buttonEmergency.setFlat(False)
        self.buttonEmergency.setObjectName(_fromUtf8("buttonEmergency"))
        self.verticalLayout.addWidget(self.buttonEmergency)
        DynoMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DynoMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuConfig = QtGui.QMenu(self.menubar)
        self.menuConfig.setObjectName(_fromUtf8("menuConfig"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSaveImage = QtGui.QMenu(self.menuFile)
        self.menuSaveImage.setObjectName(_fromUtf8("menuSaveImage"))
        self.menuProgram = QtGui.QMenu(self.menubar)
        self.menuProgram.setObjectName(_fromUtf8("menuProgram"))
        DynoMainWindow.setMenuBar(self.menubar)
        self.actionCallibrate = QtGui.QAction(DynoMainWindow)
        self.actionCallibrate.setObjectName(_fromUtf8("actionCallibrate"))
        self.actionAbout = QtGui.QAction(DynoMainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(DynoMainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSettings = QtGui.QAction(DynoMainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExportPNG = QtGui.QAction(DynoMainWindow)
        self.actionExportPNG.setObjectName(_fromUtf8("actionExportPNG"))
        self.actionExit = QtGui.QAction(DynoMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionProgram = QtGui.QAction(DynoMainWindow)
        self.actionProgram.setObjectName(_fromUtf8("actionProgram"))
        self.actionProgramManage = QtGui.QAction(DynoMainWindow)
        self.actionProgramManage.setObjectName(_fromUtf8("actionProgramManage"))
        self.actionRunProgram = QtGui.QAction(DynoMainWindow)
        self.actionRunProgram.setObjectName(_fromUtf8("actionRunProgram"))
        self.actionExportCSV = QtGui.QAction(DynoMainWindow)
        self.actionExportCSV.setObjectName(_fromUtf8("actionExportCSV"))
        self.actionExportToSVG = QtGui.QAction(DynoMainWindow)
        self.actionExportToSVG.setObjectName(_fromUtf8("actionExportToSVG"))
        self.actionExportToPNG = QtGui.QAction(DynoMainWindow)
        self.actionExportToPNG.setObjectName(_fromUtf8("actionExportToPNG"))
        self.actionExportToJPEG = QtGui.QAction(DynoMainWindow)
        self.actionExportToJPEG.setObjectName(_fromUtf8("actionExportToJPEG"))
        self.actionExportToCSV = QtGui.QAction(DynoMainWindow)
        self.actionExportToCSV.setObjectName(_fromUtf8("actionExportToCSV"))
        self.menuConfig.addAction(self.actionCallibrate)
        self.menuConfig.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuSaveImage.addSeparator()
        self.menuSaveImage.addAction(self.actionExportToSVG)
        self.menuSaveImage.addAction(self.actionExportToPNG)
        self.menuSaveImage.addAction(self.actionExportToJPEG)
        self.menuFile.addAction(self.menuSaveImage.menuAction())
        self.menuFile.addAction(self.actionExportToCSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuProgram.addAction(self.actionProgramManage)
        self.menuProgram.addAction(self.actionRunProgram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DynoMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DynoMainWindow)

    def retranslateUi(self, DynoMainWindow):
        DynoMainWindow.setWindowTitle(_translate("DynoMainWindow", "LFEV Dynamometer Control Software", None))
        self.Throttle.setText(_translate("DynoMainWindow", "Throttle Output", None))
        self.spinBoxThrottle.setSuffix(_translate("DynoMainWindow", "%", None))
        self.labelMotor.setText(_translate("DynoMainWindow", "Motor Resistance", None))
        self.spinBoxLoad.setSuffix(_translate("DynoMainWindow", "%", None))
        self.labelTorque.setText(_translate("DynoMainWindow", "Torque", None))
        self.labelTorqueUnits.setText(_translate("DynoMainWindow", "lb·ft", None))
        self.labelTach_2.setText(_translate("DynoMainWindow", "Power", None))
        self.labelPowerUnits.setText(_translate("DynoMainWindow", "hp", None))
        self.labelTach.setText(_translate("DynoMainWindow", "Speed (D)", None))
        self.labelTachUnits.setText(_translate("DynoMainWindow", "rpm", None))
        self.labelTachCAN.setText(_translate("DynoMainWindow", "Speed (MC)", None))
        self.labelTachCANUnits.setText(_translate("DynoMainWindow", "rpm", None))
        self.labelCurrent.setText(_translate("DynoMainWindow", "Current", None))
        self.labelCurrentUnits.setText(_translate("DynoMainWindow", "A", None))
        self.labelTach_3.setText(_translate("DynoMainWindow", "Voltage", None))
        self.labelVoltageUnits_2.setText(_translate("DynoMainWindow", "V", None))
        self.labelMCTemp.setText(_translate("DynoMainWindow", "Temp (MC)", None))
        self.labelMCTempUnits.setText(_translate("DynoMainWindow", "°C", None))
        self.labelMTemp.setText(_translate("DynoMainWindow", "Temp (M)", None))
        self.labelMTempUnits.setText(_translate("DynoMainWindow", "°C", None))
        self.buttonPauseData.setText(_translate("DynoMainWindow", "PAUSE", None))
        self.buttonClearData.setText(_translate("DynoMainWindow", "CLEAR DATA", None))
        self.buttonEmergency.setText(_translate("DynoMainWindow", "EMERGENCY HALT", None))
        self.menuConfig.setTitle(_translate("DynoMainWindow", "Config", None))
        self.menuHelp.setTitle(_translate("DynoMainWindow", "Help", None))
        self.menuFile.setTitle(_translate("DynoMainWindow", "File", None))
        self.menuSaveImage.setTitle(_translate("DynoMainWindow", "Save Image", None))
        self.menuProgram.setTitle(_translate("DynoMainWindow", "Program", None))
        self.actionCallibrate.setText(_translate("DynoMainWindow", "Callibrate...", None))
        self.actionAbout.setText(_translate("DynoMainWindow", "About", None))
        self.actionHelp.setText(_translate("DynoMainWindow", "Help", None))
        self.actionSettings.setText(_translate("DynoMainWindow", "Settings...", None))
        self.actionExportPNG.setText(_translate("DynoMainWindow", "Export PNG...", None))
        self.actionExit.setText(_translate("DynoMainWindow", "Exit", None))
        self.actionProgram.setText(_translate("DynoMainWindow", "Program...", None))
        self.actionProgramManage.setText(_translate("DynoMainWindow", "Manage...", None))
        self.actionRunProgram.setText(_translate("DynoMainWindow", "Run...", None))
        self.actionExportCSV.setText(_translate("DynoMainWindow", "Export CSV...", None))
        self.actionExportToSVG.setText(_translate("DynoMainWindow", "Export to SVG", None))
        self.actionExportToPNG.setText(_translate("DynoMainWindow", "Export to PNG", None))
        self.actionExportToJPEG.setText(_translate("DynoMainWindow", "Export to JPEG", None))
        self.actionExportToCSV.setText(_translate("DynoMainWindow", "Export CSV...", None))

from pyqtgraph import PlotWidget
