# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main-window.ui'
#
# Created by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(839, 703)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/general/img/lafayette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabSystemWidget = QtGui.QTabWidget(self.splitter)
        self.tabSystemWidget.setObjectName(_fromUtf8("tabSystemWidget"))
        self.tabDyno = QtGui.QWidget()
        self.tabDyno.setObjectName(_fromUtf8("tabDyno"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabDyno)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hLayoutInput = QtGui.QHBoxLayout()
        self.hLayoutInput.setObjectName(_fromUtf8("hLayoutInput"))
        self.vLayoutThrottle = QtGui.QVBoxLayout()
        self.vLayoutThrottle.setSpacing(0)
        self.vLayoutThrottle.setObjectName(_fromUtf8("vLayoutThrottle"))
        self.labelThrottle = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelThrottle.setFont(font)
        self.labelThrottle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThrottle.setObjectName(_fromUtf8("labelThrottle"))
        self.vLayoutThrottle.addWidget(self.labelThrottle)
        self.hLayoutThrottle = QtGui.QHBoxLayout()
        self.hLayoutThrottle.setObjectName(_fromUtf8("hLayoutThrottle"))
        self.hSliderThrottle = QtGui.QSlider(self.tabDyno)
        self.hSliderThrottle.setMaximum(100)
        self.hSliderThrottle.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderThrottle.setObjectName(_fromUtf8("hSliderThrottle"))
        self.hLayoutThrottle.addWidget(self.hSliderThrottle)
        self.spinBoxThrottle = QtGui.QDoubleSpinBox(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxThrottle.setFont(font)
        self.spinBoxThrottle.setDecimals(0)
        self.spinBoxThrottle.setMaximum(100.0)
        self.spinBoxThrottle.setObjectName(_fromUtf8("spinBoxThrottle"))
        self.hLayoutThrottle.addWidget(self.spinBoxThrottle)
        self.vLayoutThrottle.addLayout(self.hLayoutThrottle)
        self.hLayoutInput.addLayout(self.vLayoutThrottle)
        self.vLayoutLoad = QtGui.QVBoxLayout()
        self.vLayoutLoad.setSpacing(0)
        self.vLayoutLoad.setObjectName(_fromUtf8("vLayoutLoad"))
        self.labelLoad = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLoad.setFont(font)
        self.labelLoad.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoad.setObjectName(_fromUtf8("labelLoad"))
        self.vLayoutLoad.addWidget(self.labelLoad)
        self.hlLayoutLoad = QtGui.QHBoxLayout()
        self.hlLayoutLoad.setObjectName(_fromUtf8("hlLayoutLoad"))
        self.hSliderLoad = QtGui.QSlider(self.tabDyno)
        self.hSliderLoad.setMaximum(100)
        self.hSliderLoad.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderLoad.setObjectName(_fromUtf8("hSliderLoad"))
        self.hlLayoutLoad.addWidget(self.hSliderLoad)
        self.spinBoxLoad = QtGui.QDoubleSpinBox(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxLoad.setFont(font)
        self.spinBoxLoad.setDecimals(0)
        self.spinBoxLoad.setMaximum(100.0)
        self.spinBoxLoad.setObjectName(_fromUtf8("spinBoxLoad"))
        self.hlLayoutLoad.addWidget(self.spinBoxLoad)
        self.vLayoutLoad.addLayout(self.hlLayoutLoad)
        self.hLayoutInput.addLayout(self.vLayoutLoad)
        self.verticalLayout.addLayout(self.hLayoutInput)
        self.hLayoutOutput_1 = QtGui.QHBoxLayout()
        self.hLayoutOutput_1.setObjectName(_fromUtf8("hLayoutOutput_1"))
        self.vLayoutTorque = QtGui.QVBoxLayout()
        self.vLayoutTorque.setObjectName(_fromUtf8("vLayoutTorque"))
        self.labelTorque = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorque.setFont(font)
        self.labelTorque.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorque.setMargin(3)
        self.labelTorque.setObjectName(_fromUtf8("labelTorque"))
        self.vLayoutTorque.addWidget(self.labelTorque)
        self.hLayoutTorque = QtGui.QHBoxLayout()
        self.hLayoutTorque.setObjectName(_fromUtf8("hLayoutTorque"))
        self.lcdNumberTorque = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTorque.sizePolicy().hasHeightForWidth())
        self.lcdNumberTorque.setSizePolicy(sizePolicy)
        self.lcdNumberTorque.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberTorque.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTorque.setSmallDecimalPoint(True)
        self.lcdNumberTorque.setDigitCount(5)
        self.lcdNumberTorque.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTorque.setProperty("value", 0.0)
        self.lcdNumberTorque.setProperty("intValue", 0)
        self.lcdNumberTorque.setObjectName(_fromUtf8("lcdNumberTorque"))
        self.hLayoutTorque.addWidget(self.lcdNumberTorque)
        self.labelTorqueUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTorqueUnits.sizePolicy().hasHeightForWidth())
        self.labelTorqueUnits.setSizePolicy(sizePolicy)
        self.labelTorqueUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorqueUnits.setFont(font)
        self.labelTorqueUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorqueUnits.setMargin(5)
        self.labelTorqueUnits.setObjectName(_fromUtf8("labelTorqueUnits"))
        self.hLayoutTorque.addWidget(self.labelTorqueUnits)
        self.vLayoutTorque.addLayout(self.hLayoutTorque)
        self.hLayoutOutput_1.addLayout(self.vLayoutTorque)
        self.vLayoutPower = QtGui.QVBoxLayout()
        self.vLayoutPower.setObjectName(_fromUtf8("vLayoutPower"))
        self.labelTach_2 = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach_2.setFont(font)
        self.labelTach_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach_2.setMargin(3)
        self.labelTach_2.setObjectName(_fromUtf8("labelTach_2"))
        self.vLayoutPower.addWidget(self.labelTach_2)
        self.hLayoutPowerLCD = QtGui.QHBoxLayout()
        self.hLayoutPowerLCD.setObjectName(_fromUtf8("hLayoutPowerLCD"))
        self.lcdNumberPower = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberPower.sizePolicy().hasHeightForWidth())
        self.lcdNumberPower.setSizePolicy(sizePolicy)
        self.lcdNumberPower.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberPower.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberPower.setSmallDecimalPoint(True)
        self.lcdNumberPower.setDigitCount(5)
        self.lcdNumberPower.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberPower.setProperty("value", 0.0)
        self.lcdNumberPower.setProperty("intValue", 0)
        self.lcdNumberPower.setObjectName(_fromUtf8("lcdNumberPower"))
        self.hLayoutPowerLCD.addWidget(self.lcdNumberPower)
        self.labelPowerUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPowerUnits.sizePolicy().hasHeightForWidth())
        self.labelPowerUnits.setSizePolicy(sizePolicy)
        self.labelPowerUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPowerUnits.setFont(font)
        self.labelPowerUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPowerUnits.setMargin(5)
        self.labelPowerUnits.setObjectName(_fromUtf8("labelPowerUnits"))
        self.hLayoutPowerLCD.addWidget(self.labelPowerUnits)
        self.vLayoutPower.addLayout(self.hLayoutPowerLCD)
        self.hLayoutOutput_1.addLayout(self.vLayoutPower)
        self.vLayoutTach = QtGui.QVBoxLayout()
        self.vLayoutTach.setObjectName(_fromUtf8("vLayoutTach"))
        self.labelTach = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach.setFont(font)
        self.labelTach.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach.setMargin(3)
        self.labelTach.setObjectName(_fromUtf8("labelTach"))
        self.vLayoutTach.addWidget(self.labelTach)
        self.hLayoutTachLCD = QtGui.QHBoxLayout()
        self.hLayoutTachLCD.setObjectName(_fromUtf8("hLayoutTachLCD"))
        self.lcdNumberTach = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTach.sizePolicy().hasHeightForWidth())
        self.lcdNumberTach.setSizePolicy(sizePolicy)
        self.lcdNumberTach.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberTach.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTach.setSmallDecimalPoint(True)
        self.lcdNumberTach.setDigitCount(5)
        self.lcdNumberTach.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTach.setProperty("value", 0.0)
        self.lcdNumberTach.setProperty("intValue", 0)
        self.lcdNumberTach.setObjectName(_fromUtf8("lcdNumberTach"))
        self.hLayoutTachLCD.addWidget(self.lcdNumberTach)
        self.labelTachUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTachUnits.sizePolicy().hasHeightForWidth())
        self.labelTachUnits.setSizePolicy(sizePolicy)
        self.labelTachUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachUnits.setFont(font)
        self.labelTachUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachUnits.setMargin(5)
        self.labelTachUnits.setObjectName(_fromUtf8("labelTachUnits"))
        self.hLayoutTachLCD.addWidget(self.labelTachUnits)
        self.vLayoutTach.addLayout(self.hLayoutTachLCD)
        self.hLayoutOutput_1.addLayout(self.vLayoutTach)
        self.vLayoutTachCAN = QtGui.QVBoxLayout()
        self.vLayoutTachCAN.setObjectName(_fromUtf8("vLayoutTachCAN"))
        self.labelTachCAN = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachCAN.setFont(font)
        self.labelTachCAN.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachCAN.setMargin(3)
        self.labelTachCAN.setObjectName(_fromUtf8("labelTachCAN"))
        self.vLayoutTachCAN.addWidget(self.labelTachCAN)
        self.hLayoutTachCAN = QtGui.QHBoxLayout()
        self.hLayoutTachCAN.setObjectName(_fromUtf8("hLayoutTachCAN"))
        self.lcdNumberTachCAN = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTachCAN.sizePolicy().hasHeightForWidth())
        self.lcdNumberTachCAN.setSizePolicy(sizePolicy)
        self.lcdNumberTachCAN.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberTachCAN.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberTachCAN.setSmallDecimalPoint(True)
        self.lcdNumberTachCAN.setDigitCount(5)
        self.lcdNumberTachCAN.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberTachCAN.setProperty("value", 0.0)
        self.lcdNumberTachCAN.setProperty("intValue", 0)
        self.lcdNumberTachCAN.setObjectName(_fromUtf8("lcdNumberTachCAN"))
        self.hLayoutTachCAN.addWidget(self.lcdNumberTachCAN)
        self.labelTachCANUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTachCANUnits.sizePolicy().hasHeightForWidth())
        self.labelTachCANUnits.setSizePolicy(sizePolicy)
        self.labelTachCANUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTachCANUnits.setFont(font)
        self.labelTachCANUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTachCANUnits.setMargin(5)
        self.labelTachCANUnits.setObjectName(_fromUtf8("labelTachCANUnits"))
        self.hLayoutTachCAN.addWidget(self.labelTachCANUnits)
        self.vLayoutTachCAN.addLayout(self.hLayoutTachCAN)
        self.hLayoutOutput_1.addLayout(self.vLayoutTachCAN)
        self.verticalLayout.addLayout(self.hLayoutOutput_1)
        self.hLayoutOutput_2 = QtGui.QHBoxLayout()
        self.hLayoutOutput_2.setObjectName(_fromUtf8("hLayoutOutput_2"))
        self.vLayoutCurrent = QtGui.QVBoxLayout()
        self.vLayoutCurrent.setObjectName(_fromUtf8("vLayoutCurrent"))
        self.labelCurrent = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrent.setFont(font)
        self.labelCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrent.setMargin(3)
        self.labelCurrent.setObjectName(_fromUtf8("labelCurrent"))
        self.vLayoutCurrent.addWidget(self.labelCurrent)
        self.hLayoutCurrentLCD = QtGui.QHBoxLayout()
        self.hLayoutCurrentLCD.setObjectName(_fromUtf8("hLayoutCurrentLCD"))
        self.lcdNumberCurrent = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberCurrent.sizePolicy().hasHeightForWidth())
        self.lcdNumberCurrent.setSizePolicy(sizePolicy)
        self.lcdNumberCurrent.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberCurrent.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberCurrent.setSmallDecimalPoint(True)
        self.lcdNumberCurrent.setDigitCount(5)
        self.lcdNumberCurrent.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberCurrent.setProperty("value", 0.0)
        self.lcdNumberCurrent.setProperty("intValue", 0)
        self.lcdNumberCurrent.setObjectName(_fromUtf8("lcdNumberCurrent"))
        self.hLayoutCurrentLCD.addWidget(self.lcdNumberCurrent)
        self.labelCurrentUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentUnits.sizePolicy().hasHeightForWidth())
        self.labelCurrentUnits.setSizePolicy(sizePolicy)
        self.labelCurrentUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentUnits.setFont(font)
        self.labelCurrentUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentUnits.setMargin(5)
        self.labelCurrentUnits.setObjectName(_fromUtf8("labelCurrentUnits"))
        self.hLayoutCurrentLCD.addWidget(self.labelCurrentUnits)
        self.vLayoutCurrent.addLayout(self.hLayoutCurrentLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutCurrent)
        self.vLayoutVoltage = QtGui.QVBoxLayout()
        self.vLayoutVoltage.setObjectName(_fromUtf8("vLayoutVoltage"))
        self.labelTach_3 = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTach_3.setFont(font)
        self.labelTach_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTach_3.setMargin(3)
        self.labelTach_3.setObjectName(_fromUtf8("labelTach_3"))
        self.vLayoutVoltage.addWidget(self.labelTach_3)
        self.hLayoutVoltageLCD = QtGui.QHBoxLayout()
        self.hLayoutVoltageLCD.setObjectName(_fromUtf8("hLayoutVoltageLCD"))
        self.lcdNumberVoltage = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberVoltage.sizePolicy().hasHeightForWidth())
        self.lcdNumberVoltage.setSizePolicy(sizePolicy)
        self.lcdNumberVoltage.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberVoltage.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberVoltage.setSmallDecimalPoint(True)
        self.lcdNumberVoltage.setDigitCount(5)
        self.lcdNumberVoltage.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberVoltage.setProperty("value", 0.0)
        self.lcdNumberVoltage.setProperty("intValue", 0)
        self.lcdNumberVoltage.setObjectName(_fromUtf8("lcdNumberVoltage"))
        self.hLayoutVoltageLCD.addWidget(self.lcdNumberVoltage)
        self.labelVoltageUnits_2 = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVoltageUnits_2.sizePolicy().hasHeightForWidth())
        self.labelVoltageUnits_2.setSizePolicy(sizePolicy)
        self.labelVoltageUnits_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVoltageUnits_2.setFont(font)
        self.labelVoltageUnits_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVoltageUnits_2.setMargin(5)
        self.labelVoltageUnits_2.setObjectName(_fromUtf8("labelVoltageUnits_2"))
        self.hLayoutVoltageLCD.addWidget(self.labelVoltageUnits_2)
        self.vLayoutVoltage.addLayout(self.hLayoutVoltageLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutVoltage)
        self.vLayoutMCTemp = QtGui.QVBoxLayout()
        self.vLayoutMCTemp.setObjectName(_fromUtf8("vLayoutMCTemp"))
        self.labelMCTemp = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelMCTemp.setFont(font)
        self.labelMCTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMCTemp.setMargin(3)
        self.labelMCTemp.setObjectName(_fromUtf8("labelMCTemp"))
        self.vLayoutMCTemp.addWidget(self.labelMCTemp)
        self.hLayoutMCTempLCD = QtGui.QHBoxLayout()
        self.hLayoutMCTempLCD.setObjectName(_fromUtf8("hLayoutMCTempLCD"))
        self.lcdNumberMCTemp = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberMCTemp.sizePolicy().hasHeightForWidth())
        self.lcdNumberMCTemp.setSizePolicy(sizePolicy)
        self.lcdNumberMCTemp.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberMCTemp.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberMCTemp.setSmallDecimalPoint(True)
        self.lcdNumberMCTemp.setDigitCount(5)
        self.lcdNumberMCTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberMCTemp.setProperty("value", 0.0)
        self.lcdNumberMCTemp.setProperty("intValue", 0)
        self.lcdNumberMCTemp.setObjectName(_fromUtf8("lcdNumberMCTemp"))
        self.hLayoutMCTempLCD.addWidget(self.lcdNumberMCTemp)
        self.labelMCTempUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMCTempUnits.sizePolicy().hasHeightForWidth())
        self.labelMCTempUnits.setSizePolicy(sizePolicy)
        self.labelMCTempUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMCTempUnits.setFont(font)
        self.labelMCTempUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMCTempUnits.setMargin(5)
        self.labelMCTempUnits.setObjectName(_fromUtf8("labelMCTempUnits"))
        self.hLayoutMCTempLCD.addWidget(self.labelMCTempUnits)
        self.vLayoutMCTemp.addLayout(self.hLayoutMCTempLCD)
        self.hLayoutOutput_2.addLayout(self.vLayoutMCTemp)
        self.vLayoutMTemp = QtGui.QVBoxLayout()
        self.vLayoutMTemp.setObjectName(_fromUtf8("vLayoutMTemp"))
        self.labelMTemp = QtGui.QLabel(self.tabDyno)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelMTemp.setFont(font)
        self.labelMTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMTemp.setMargin(3)
        self.labelMTemp.setObjectName(_fromUtf8("labelMTemp"))
        self.vLayoutMTemp.addWidget(self.labelMTemp)
        self.hLayoutMTemp = QtGui.QHBoxLayout()
        self.hLayoutMTemp.setObjectName(_fromUtf8("hLayoutMTemp"))
        self.lcdNumberMTemp = QtGui.QLCDNumber(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberMTemp.sizePolicy().hasHeightForWidth())
        self.lcdNumberMTemp.setSizePolicy(sizePolicy)
        self.lcdNumberMTemp.setMinimumSize(QtCore.QSize(125, 40))
        self.lcdNumberMTemp.setStyleSheet(_fromUtf8("background-color: white;"))
        self.lcdNumberMTemp.setSmallDecimalPoint(True)
        self.lcdNumberMTemp.setDigitCount(5)
        self.lcdNumberMTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberMTemp.setProperty("value", 0.0)
        self.lcdNumberMTemp.setProperty("intValue", 0)
        self.lcdNumberMTemp.setObjectName(_fromUtf8("lcdNumberMTemp"))
        self.hLayoutMTemp.addWidget(self.lcdNumberMTemp)
        self.labelMTempUnits = QtGui.QLabel(self.tabDyno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMTempUnits.sizePolicy().hasHeightForWidth())
        self.labelMTempUnits.setSizePolicy(sizePolicy)
        self.labelMTempUnits.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMTempUnits.setFont(font)
        self.labelMTempUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMTempUnits.setMargin(5)
        self.labelMTempUnits.setObjectName(_fromUtf8("labelMTempUnits"))
        self.hLayoutMTemp.addWidget(self.labelMTempUnits)
        self.vLayoutMTemp.addLayout(self.hLayoutMTemp)
        self.hLayoutOutput_2.addLayout(self.vLayoutMTemp)
        self.verticalLayout.addLayout(self.hLayoutOutput_2)
        self.dynoDataPlot = PlotWidget(self.tabDyno)
        self.dynoDataPlot.setMinimumSize(QtCore.QSize(0, 200))
        self.dynoDataPlot.setObjectName(_fromUtf8("dynoDataPlot"))
        self.verticalLayout.addWidget(self.dynoDataPlot)
        self.hLayoutDataButtons = QtGui.QHBoxLayout()
        self.hLayoutDataButtons.setObjectName(_fromUtf8("hLayoutDataButtons"))
        self.buttonPauseData = QtGui.QPushButton(self.tabDyno)
        self.buttonPauseData.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPauseData.setFont(font)
        self.buttonPauseData.setCheckable(True)
        self.buttonPauseData.setDefault(False)
        self.buttonPauseData.setFlat(False)
        self.buttonPauseData.setObjectName(_fromUtf8("buttonPauseData"))
        self.hLayoutDataButtons.addWidget(self.buttonPauseData)
        self.buttonClearData = QtGui.QPushButton(self.tabDyno)
        self.buttonClearData.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonClearData.setFont(font)
        self.buttonClearData.setDefault(False)
        self.buttonClearData.setFlat(False)
        self.buttonClearData.setObjectName(_fromUtf8("buttonClearData"))
        self.hLayoutDataButtons.addWidget(self.buttonClearData)
        self.verticalLayout.addLayout(self.hLayoutDataButtons)
        self.buttonEmergency = QtGui.QPushButton(self.tabDyno)
        self.buttonEmergency.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEmergency.setFont(font)
        self.buttonEmergency.setStyleSheet(_fromUtf8("background-color: red;"))
        self.buttonEmergency.setDefault(False)
        self.buttonEmergency.setFlat(False)
        self.buttonEmergency.setObjectName(_fromUtf8("buttonEmergency"))
        self.verticalLayout.addWidget(self.buttonEmergency)
        self.tabSystemWidget.addTab(self.tabDyno, _fromUtf8(""))
        self.tabPowerSupply = QtGui.QWidget()
        self.tabPowerSupply.setObjectName(_fromUtf8("tabPowerSupply"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabPowerSupply)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.labelPSU = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPSU.sizePolicy().hasHeightForWidth())
        self.labelPSU.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelPSU.setFont(font)
        self.labelPSU.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSU.setObjectName(_fromUtf8("labelPSU"))
        self.verticalLayout_6.addWidget(self.labelPSU)
        self.labelPSURIS = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPSURIS.sizePolicy().hasHeightForWidth())
        self.labelPSURIS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelPSURIS.setFont(font)
        self.labelPSURIS.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSURIS.setObjectName(_fromUtf8("labelPSURIS"))
        self.verticalLayout_6.addWidget(self.labelPSURIS)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.hLayoutVoltCurr = QtGui.QHBoxLayout()
        self.hLayoutVoltCurr.setObjectName(_fromUtf8("hLayoutVoltCurr"))
        self.vLayoutPSUVoltage = QtGui.QVBoxLayout()
        self.vLayoutPSUVoltage.setObjectName(_fromUtf8("vLayoutPSUVoltage"))
        self.labelPSUVoltage = QtGui.QLabel(self.tabPowerSupply)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPSUVoltage.setFont(font)
        self.labelPSUVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSUVoltage.setMargin(3)
        self.labelPSUVoltage.setObjectName(_fromUtf8("labelPSUVoltage"))
        self.vLayoutPSUVoltage.addWidget(self.labelPSUVoltage)
        self.spinBoxPSUVoltage = QtGui.QDoubleSpinBox(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxPSUVoltage.sizePolicy().hasHeightForWidth())
        self.spinBoxPSUVoltage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxPSUVoltage.setFont(font)
        self.spinBoxPSUVoltage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxPSUVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxPSUVoltage.setDecimals(1)
        self.spinBoxPSUVoltage.setMaximum(150.0)
        self.spinBoxPSUVoltage.setSingleStep(0.1)
        self.spinBoxPSUVoltage.setProperty("value", 89.6)
        self.spinBoxPSUVoltage.setObjectName(_fromUtf8("spinBoxPSUVoltage"))
        self.vLayoutPSUVoltage.addWidget(self.spinBoxPSUVoltage)
        self.hLayoutVoltCurr.addLayout(self.vLayoutPSUVoltage)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hLayoutVoltCurr.addItem(spacerItem2)
        self.vLayoutPSUCurrent = QtGui.QVBoxLayout()
        self.vLayoutPSUCurrent.setObjectName(_fromUtf8("vLayoutPSUCurrent"))
        self.labelPSUCurrent = QtGui.QLabel(self.tabPowerSupply)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPSUCurrent.setFont(font)
        self.labelPSUCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSUCurrent.setMargin(3)
        self.labelPSUCurrent.setObjectName(_fromUtf8("labelPSUCurrent"))
        self.vLayoutPSUCurrent.addWidget(self.labelPSUCurrent)
        self.spinBoxPSUCurrent = QtGui.QDoubleSpinBox(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxPSUCurrent.sizePolicy().hasHeightForWidth())
        self.spinBoxPSUCurrent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxPSUCurrent.setFont(font)
        self.spinBoxPSUCurrent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxPSUCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxPSUCurrent.setDecimals(1)
        self.spinBoxPSUCurrent.setMaximum(275.0)
        self.spinBoxPSUCurrent.setSingleStep(0.1)
        self.spinBoxPSUCurrent.setProperty("value", 200.0)
        self.spinBoxPSUCurrent.setObjectName(_fromUtf8("spinBoxPSUCurrent"))
        self.vLayoutPSUCurrent.addWidget(self.spinBoxPSUCurrent)
        self.hLayoutVoltCurr.addLayout(self.vLayoutPSUCurrent)
        self.verticalLayout_6.addLayout(self.hLayoutVoltCurr)
        self.hLayoutVoltCurr_2 = QtGui.QHBoxLayout()
        self.hLayoutVoltCurr_2.setObjectName(_fromUtf8("hLayoutVoltCurr_2"))
        self.vLayoutPSUVoltage_2 = QtGui.QVBoxLayout()
        self.vLayoutPSUVoltage_2.setObjectName(_fromUtf8("vLayoutPSUVoltage_2"))
        self.labelPSUVoltage_2 = QtGui.QLabel(self.tabPowerSupply)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPSUVoltage_2.setFont(font)
        self.labelPSUVoltage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSUVoltage_2.setMargin(3)
        self.labelPSUVoltage_2.setObjectName(_fromUtf8("labelPSUVoltage_2"))
        self.vLayoutPSUVoltage_2.addWidget(self.labelPSUVoltage_2)
        self.hLayoutTorque_2 = QtGui.QHBoxLayout()
        self.hLayoutTorque_2.setObjectName(_fromUtf8("hLayoutTorque_2"))
        self.label = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.hLayoutTorque_2.addWidget(self.label)
        self.labelTorqueUnits_2 = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTorqueUnits_2.sizePolicy().hasHeightForWidth())
        self.labelTorqueUnits_2.setSizePolicy(sizePolicy)
        self.labelTorqueUnits_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorqueUnits_2.setFont(font)
        self.labelTorqueUnits_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorqueUnits_2.setMargin(5)
        self.labelTorqueUnits_2.setObjectName(_fromUtf8("labelTorqueUnits_2"))
        self.hLayoutTorque_2.addWidget(self.labelTorqueUnits_2)
        self.vLayoutPSUVoltage_2.addLayout(self.hLayoutTorque_2)
        self.hLayoutVoltCurr_2.addLayout(self.vLayoutPSUVoltage_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hLayoutVoltCurr_2.addItem(spacerItem3)
        self.vLayoutPSUCurrent_3 = QtGui.QVBoxLayout()
        self.vLayoutPSUCurrent_3.setObjectName(_fromUtf8("vLayoutPSUCurrent_3"))
        self.labelPSUCurrent_3 = QtGui.QLabel(self.tabPowerSupply)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPSUCurrent_3.setFont(font)
        self.labelPSUCurrent_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPSUCurrent_3.setMargin(3)
        self.labelPSUCurrent_3.setObjectName(_fromUtf8("labelPSUCurrent_3"))
        self.vLayoutPSUCurrent_3.addWidget(self.labelPSUCurrent_3)
        self.hLayoutTorque_3 = QtGui.QHBoxLayout()
        self.hLayoutTorque_3.setObjectName(_fromUtf8("hLayoutTorque_3"))
        self.label_2 = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hLayoutTorque_3.addWidget(self.label_2)
        self.labelTorqueUnits_3 = QtGui.QLabel(self.tabPowerSupply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTorqueUnits_3.sizePolicy().hasHeightForWidth())
        self.labelTorqueUnits_3.setSizePolicy(sizePolicy)
        self.labelTorqueUnits_3.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelTorqueUnits_3.setFont(font)
        self.labelTorqueUnits_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTorqueUnits_3.setMargin(5)
        self.labelTorqueUnits_3.setObjectName(_fromUtf8("labelTorqueUnits_3"))
        self.hLayoutTorque_3.addWidget(self.labelTorqueUnits_3)
        self.vLayoutPSUCurrent_3.addLayout(self.hLayoutTorque_3)
        self.hLayoutVoltCurr_2.addLayout(self.vLayoutPSUCurrent_3)
        self.verticalLayout_6.addLayout(self.hLayoutVoltCurr_2)
        self.psuDataPlot = PlotWidget(self.tabPowerSupply)
        self.psuDataPlot.setMinimumSize(QtCore.QSize(0, 200))
        self.psuDataPlot.setObjectName(_fromUtf8("psuDataPlot"))
        self.verticalLayout_6.addWidget(self.psuDataPlot)
        self.hLayoutState = QtGui.QHBoxLayout()
        self.hLayoutState.setObjectName(_fromUtf8("hLayoutState"))
        self.buttonPSUOn = QtGui.QPushButton(self.tabPowerSupply)
        self.buttonPSUOn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPSUOn.setFont(font)
        self.buttonPSUOn.setCheckable(False)
        self.buttonPSUOn.setDefault(False)
        self.buttonPSUOn.setFlat(False)
        self.buttonPSUOn.setObjectName(_fromUtf8("buttonPSUOn"))
        self.hLayoutState.addWidget(self.buttonPSUOn)
        self.buttonPSUOff = QtGui.QPushButton(self.tabPowerSupply)
        self.buttonPSUOff.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPSUOff.setFont(font)
        self.buttonPSUOff.setCheckable(False)
        self.buttonPSUOff.setDefault(False)
        self.buttonPSUOff.setFlat(False)
        self.buttonPSUOff.setObjectName(_fromUtf8("buttonPSUOff"))
        self.hLayoutState.addWidget(self.buttonPSUOff)
        self.verticalLayout_6.addLayout(self.hLayoutState)
        self.tabSystemWidget.addTab(self.tabPowerSupply, _fromUtf8(""))
        self.tabMsgWidget = QtGui.QTabWidget(self.splitter)
        self.tabMsgWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabMsgWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabMsgWidget.setObjectName(_fromUtf8("tabMsgWidget"))
        self.tabMsgs = QtGui.QWidget()
        self.tabMsgs.setObjectName(_fromUtf8("tabMsgs"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabMsgs)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.plainTextEditMsgs = QtGui.QPlainTextEdit(self.tabMsgs)
        self.plainTextEditMsgs.setPlainText(_fromUtf8(""))
        self.plainTextEditMsgs.setObjectName(_fromUtf8("plainTextEditMsgs"))
        self.verticalLayout_3.addWidget(self.plainTextEditMsgs)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/oxygen/img/message.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMsgWidget.addTab(self.tabMsgs, icon1, _fromUtf8(""))
        self.tabWarn = QtGui.QWidget()
        self.tabWarn.setObjectName(_fromUtf8("tabWarn"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabWarn)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.plainTextEditWarn = QtGui.QPlainTextEdit(self.tabWarn)
        self.plainTextEditWarn.setPlainText(_fromUtf8(""))
        self.plainTextEditWarn.setObjectName(_fromUtf8("plainTextEditWarn"))
        self.verticalLayout_4.addWidget(self.plainTextEditWarn)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/oxygen/img/warning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMsgWidget.addTab(self.tabWarn, icon2, _fromUtf8(""))
        self.tabErr = QtGui.QWidget()
        self.tabErr.setObjectName(_fromUtf8("tabErr"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabErr)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.plainTextEditErr = QtGui.QPlainTextEdit(self.tabErr)
        self.plainTextEditErr.setPlainText(_fromUtf8(""))
        self.plainTextEditErr.setObjectName(_fromUtf8("plainTextEditErr"))
        self.verticalLayout_5.addWidget(self.plainTextEditErr)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/oxygen/img/error.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMsgWidget.addTab(self.tabErr, icon3, _fromUtf8(""))
        self.tabDebug = QtGui.QWidget()
        self.tabDebug.setObjectName(_fromUtf8("tabDebug"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabDebug)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plainTextEditDebug = QtGui.QPlainTextEdit(self.tabDebug)
        self.plainTextEditDebug.setPlainText(_fromUtf8(""))
        self.plainTextEditDebug.setObjectName(_fromUtf8("plainTextEditDebug"))
        self.verticalLayout_2.addWidget(self.plainTextEditDebug)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/oxygen/img/bug.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabMsgWidget.addTab(self.tabDebug, icon4, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 839, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConfig = QtGui.QMenu(self.menuBar)
        self.menuConfig.setObjectName(_fromUtf8("menuConfig"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCalibrate = QtGui.QAction(MainWindow)
        self.actionCalibrate.setObjectName(_fromUtf8("actionCalibrate"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionManage = QtGui.QAction(MainWindow)
        self.actionManage.setObjectName(_fromUtf8("actionManage"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuConfig.addAction(self.actionCalibrate)
        self.menuConfig.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuConfig.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabSystemWidget.setCurrentIndex(0)
        self.tabMsgWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "VSCADA Maintenance", None))
        self.labelThrottle.setText(_translate("MainWindow", "Throttle", None))
        self.spinBoxThrottle.setSuffix(_translate("MainWindow", "%", None))
        self.labelLoad.setText(_translate("MainWindow", "Resistance", None))
        self.spinBoxLoad.setSuffix(_translate("MainWindow", "%", None))
        self.labelTorque.setText(_translate("MainWindow", "Torque", None))
        self.labelTorqueUnits.setText(_translate("MainWindow", "lb·ft", None))
        self.labelTach_2.setText(_translate("MainWindow", "Power", None))
        self.labelPowerUnits.setText(_translate("MainWindow", "hp", None))
        self.labelTach.setText(_translate("MainWindow", "Speed (D)", None))
        self.labelTachUnits.setText(_translate("MainWindow", "rpm", None))
        self.labelTachCAN.setText(_translate("MainWindow", "Speed (MC)", None))
        self.labelTachCANUnits.setText(_translate("MainWindow", "rpm", None))
        self.labelCurrent.setText(_translate("MainWindow", "Current", None))
        self.labelCurrentUnits.setText(_translate("MainWindow", "A", None))
        self.labelTach_3.setText(_translate("MainWindow", "Voltage", None))
        self.labelVoltageUnits_2.setText(_translate("MainWindow", "V", None))
        self.labelMCTemp.setText(_translate("MainWindow", "Temp (MC)", None))
        self.labelMCTempUnits.setText(_translate("MainWindow", "°C", None))
        self.labelMTemp.setText(_translate("MainWindow", "Temp (M)", None))
        self.labelMTempUnits.setText(_translate("MainWindow", "°C", None))
        self.buttonPauseData.setText(_translate("MainWindow", "PAUSE", None))
        self.buttonClearData.setText(_translate("MainWindow", "CLEAR DATA", None))
        self.buttonEmergency.setText(_translate("MainWindow", "EMERGENCY HALT", None))
        self.tabSystemWidget.setTabText(self.tabSystemWidget.indexOf(self.tabDyno), _translate("MainWindow", "Dyno Monitor", None))
        self.labelPSU.setText(_translate("MainWindow", "HV Power Supply", None))
        self.labelPSURIS.setText(_translate("MainWindow", "Remote Control Interface", None))
        self.labelPSUVoltage.setText(_translate("MainWindow", "Voltage Limit", None))
        self.spinBoxPSUVoltage.setSuffix(_translate("MainWindow", " V", None))
        self.labelPSUCurrent.setText(_translate("MainWindow", "Current Limit", None))
        self.spinBoxPSUCurrent.setSuffix(_translate("MainWindow", " A", None))
        self.labelPSUVoltage_2.setText(_translate("MainWindow", "Voltage Reading", None))
        self.label.setText(_translate("MainWindow", "0.0", None))
        self.labelTorqueUnits_2.setText(_translate("MainWindow", "V", None))
        self.labelPSUCurrent_3.setText(_translate("MainWindow", "Current Reading", None))
        self.label_2.setText(_translate("MainWindow", "0.0", None))
        self.labelTorqueUnits_3.setText(_translate("MainWindow", "A", None))
        self.buttonPSUOn.setText(_translate("MainWindow", "ON", None))
        self.buttonPSUOff.setText(_translate("MainWindow", "OFF", None))
        self.tabSystemWidget.setTabText(self.tabSystemWidget.indexOf(self.tabPowerSupply), _translate("MainWindow", "Power Supply", None))
        self.tabMsgWidget.setTabText(self.tabMsgWidget.indexOf(self.tabMsgs), _translate("MainWindow", "Messages", None))
        self.tabMsgWidget.setTabText(self.tabMsgWidget.indexOf(self.tabWarn), _translate("MainWindow", "Warnings", None))
        self.tabMsgWidget.setTabText(self.tabMsgWidget.indexOf(self.tabErr), _translate("MainWindow", "Errors", None))
        self.tabMsgWidget.setTabText(self.tabMsgWidget.indexOf(self.tabDebug), _translate("MainWindow", "Debug", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuConfig.setTitle(_translate("MainWindow", "Config", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate Dyno...", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))
        self.actionManage.setText(_translate("MainWindow", "Manage...", None))
        self.actionRun.setText(_translate("MainWindow", "Run...", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save Data...", None))

from pyqtgraph import PlotWidget
import icon_rc
