# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/sensor-edit-dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(436, 666)
        Dialog.setMinimumSize(QtCore.QSize(400, 310))
        Dialog.setMaximumSize(QtCore.QSize(799, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/general/img/lafayette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_systemType = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_systemType.setFont(font)
        self.label_systemType.setObjectName(_fromUtf8("label_systemType"))
        self.horizontalLayout_2.addWidget(self.label_systemType)
        self.comboBox_systemType = QtGui.QComboBox(Dialog)
        self.comboBox_systemType.setObjectName(_fromUtf8("comboBox_systemType"))
        self.comboBox_systemType.addItem(_fromUtf8(""))
        self.comboBox_systemType.addItem(_fromUtf8(""))
        self.comboBox_systemType.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_systemType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_sensorName_2 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sensorName_2.setFont(font)
        self.label_sensorName_2.setObjectName(_fromUtf8("label_sensorName_2"))
        self.horizontalLayout_11.addWidget(self.label_sensorName_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.lineEdit_sensorName = QtGui.QLineEdit(Dialog)
        self.lineEdit_sensorName.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_sensorName.setText(_fromUtf8(""))
        self.lineEdit_sensorName.setObjectName(_fromUtf8("lineEdit_sensorName"))
        self.horizontalLayout_11.addWidget(self.lineEdit_sensorName)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_canID = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_canID.setFont(font)
        self.label_canID.setObjectName(_fromUtf8("label_canID"))
        self.horizontalLayout_4.addWidget(self.label_canID)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lineEdit_canID = QtGui.QLineEdit(Dialog)
        self.lineEdit_canID.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_canID.setText(_fromUtf8(""))
        self.lineEdit_canID.setObjectName(_fromUtf8("lineEdit_canID"))
        self.horizontalLayout_4.addWidget(self.lineEdit_canID)
        self.label_canIDInvalid = QtGui.QLabel(Dialog)
        self.label_canIDInvalid.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_canIDInvalid.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_canIDInvalid.setFont(font)
        self.label_canIDInvalid.setObjectName(_fromUtf8("label_canIDInvalid"))
        self.horizontalLayout_4.addWidget(self.label_canIDInvalid)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_canStartByte = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_canStartByte.setFont(font)
        self.label_canStartByte.setObjectName(_fromUtf8("label_canStartByte"))
        self.horizontalLayout_17.addWidget(self.label_canStartByte)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.comboBox_canStartByte = QtGui.QComboBox(Dialog)
        self.comboBox_canStartByte.setObjectName(_fromUtf8("comboBox_canStartByte"))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.comboBox_canStartByte.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.comboBox_canStartByte)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_canByteAmount = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_canByteAmount.setFont(font)
        self.label_canByteAmount.setObjectName(_fromUtf8("label_canByteAmount"))
        self.horizontalLayout_18.addWidget(self.label_canByteAmount)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.comboBox_canByteAmount = QtGui.QComboBox(Dialog)
        self.comboBox_canByteAmount.setObjectName(_fromUtf8("comboBox_canByteAmount"))
        self.comboBox_canByteAmount.addItem(_fromUtf8(""))
        self.comboBox_canByteAmount.addItem(_fromUtf8(""))
        self.comboBox_canByteAmount.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.comboBox_canByteAmount)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(8, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_calibration = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calibration.sizePolicy().hasHeightForWidth())
        self.label_calibration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_calibration.setFont(font)
        self.label_calibration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_calibration.setWordWrap(False)
        self.label_calibration.setObjectName(_fromUtf8("label_calibration"))
        self.verticalLayout_3.addWidget(self.label_calibration)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_square = QtGui.QLabel(Dialog)
        self.label_square.setObjectName(_fromUtf8("label_square"))
        self.horizontalLayout_8.addWidget(self.label_square)
        self.lineEdit_square = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_square.sizePolicy().hasHeightForWidth())
        self.lineEdit_square.setSizePolicy(sizePolicy)
        self.lineEdit_square.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_square.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit_square.setObjectName(_fromUtf8("lineEdit_square"))
        self.horizontalLayout_8.addWidget(self.lineEdit_square)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_linear = QtGui.QLabel(Dialog)
        self.label_linear.setObjectName(_fromUtf8("label_linear"))
        self.horizontalLayout_9.addWidget(self.label_linear)
        self.lineEdit_linear = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_linear.sizePolicy().hasHeightForWidth())
        self.lineEdit_linear.setSizePolicy(sizePolicy)
        self.lineEdit_linear.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_linear.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit_linear.setObjectName(_fromUtf8("lineEdit_linear"))
        self.horizontalLayout_9.addWidget(self.lineEdit_linear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_constant = QtGui.QLabel(Dialog)
        self.label_constant.setObjectName(_fromUtf8("label_constant"))
        self.horizontalLayout_14.addWidget(self.label_constant)
        self.lineEdit_constant = QtGui.QLineEdit(Dialog)
        self.lineEdit_constant.setObjectName(_fromUtf8("lineEdit_constant"))
        self.horizontalLayout_14.addWidget(self.lineEdit_constant)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_inverse = QtGui.QLabel(Dialog)
        self.label_inverse.setObjectName(_fromUtf8("label_inverse"))
        self.horizontalLayout_15.addWidget(self.label_inverse)
        self.lineEdit_inverse = QtGui.QLineEdit(Dialog)
        self.lineEdit_inverse.setObjectName(_fromUtf8("lineEdit_inverse"))
        self.horizontalLayout_15.addWidget(self.lineEdit_inverse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_inverseSquare = QtGui.QLabel(Dialog)
        self.label_inverseSquare.setObjectName(_fromUtf8("label_inverseSquare"))
        self.horizontalLayout_16.addWidget(self.label_inverseSquare)
        self.lineEdit_inverseSquare = QtGui.QLineEdit(Dialog)
        self.lineEdit_inverseSquare.setObjectName(_fromUtf8("lineEdit_inverseSquare"))
        self.horizontalLayout_16.addWidget(self.lineEdit_inverseSquare)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_sensorUnits = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sensorUnits.setFont(font)
        self.label_sensorUnits.setObjectName(_fromUtf8("label_sensorUnits"))
        self.horizontalLayout_7.addWidget(self.label_sensorUnits)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.comboBox_sensorUnits = QtGui.QComboBox(Dialog)
        self.comboBox_sensorUnits.setMinimumSize(QtCore.QSize(175, 0))
        self.comboBox_sensorUnits.setObjectName(_fromUtf8("comboBox_sensorUnits"))
        self.comboBox_sensorUnits.addItem(_fromUtf8(""))
        self.comboBox_sensorUnits.addItem(_fromUtf8(""))
        self.comboBox_sensorUnits.addItem(_fromUtf8(""))
        self.comboBox_sensorUnits.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox_sensorUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_sensorType = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sensorType.setFont(font)
        self.label_sensorType.setObjectName(_fromUtf8("label_sensorType"))
        self.horizontalLayout_6.addWidget(self.label_sensorType)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.comboBox_sensorType = QtGui.QComboBox(Dialog)
        self.comboBox_sensorType.setMinimumSize(QtCore.QSize(175, 0))
        self.comboBox_sensorType.setObjectName(_fromUtf8("comboBox_sensorType"))
        self.comboBox_sensorType.addItem(_fromUtf8(""))
        self.comboBox_sensorType.addItem(_fromUtf8(""))
        self.comboBox_sensorType.addItem(_fromUtf8(""))
        self.comboBox_sensorType.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_sensorType)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_samplingRate = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_samplingRate.setFont(font)
        self.label_samplingRate.setObjectName(_fromUtf8("label_samplingRate"))
        self.horizontalLayout.addWidget(self.label_samplingRate)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.lineEdit_samplingRate = QtGui.QLineEdit(Dialog)
        self.lineEdit_samplingRate.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_samplingRate.setMaximumSize(QtCore.QSize(180, 180))
        self.lineEdit_samplingRate.setText(_fromUtf8(""))
        self.lineEdit_samplingRate.setObjectName(_fromUtf8("lineEdit_samplingRate"))
        self.horizontalLayout.addWidget(self.lineEdit_samplingRate)
        self.label_samplingRateInvalid = QtGui.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_samplingRateInvalid.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_samplingRateInvalid.setFont(font)
        self.label_samplingRateInvalid.setObjectName(_fromUtf8("label_samplingRateInvalid"))
        self.horizontalLayout.addWidget(self.label_samplingRateInvalid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_overwritePeriod = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_overwritePeriod.setFont(font)
        self.label_overwritePeriod.setObjectName(_fromUtf8("label_overwritePeriod"))
        self.horizontalLayout_10.addWidget(self.label_overwritePeriod)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.lineEdit_overwritePeriod = QtGui.QLineEdit(Dialog)
        self.lineEdit_overwritePeriod.setText(_fromUtf8(""))
        self.lineEdit_overwritePeriod.setObjectName(_fromUtf8("lineEdit_overwritePeriod"))
        self.horizontalLayout_10.addWidget(self.lineEdit_overwritePeriod)
        self.label_overwritePeriodInvalid = QtGui.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_overwritePeriodInvalid.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_overwritePeriodInvalid.setFont(font)
        self.label_overwritePeriodInvalid.setObjectName(_fromUtf8("label_overwritePeriodInvalid"))
        self.horizontalLayout_10.addWidget(self.label_overwritePeriodInvalid)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_value = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_value.setFont(font)
        self.label_value.setObjectName(_fromUtf8("label_value"))
        self.horizontalLayout_12.addWidget(self.label_value)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.lineEdit_value = QtGui.QLineEdit(Dialog)
        self.lineEdit_value.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_value.setMaximumSize(QtCore.QSize(180, 180))
        self.lineEdit_value.setText(_fromUtf8(""))
        self.lineEdit_value.setObjectName(_fromUtf8("lineEdit_value"))
        self.horizontalLayout_12.addWidget(self.lineEdit_value)
        self.label_valueInvalid = QtGui.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_valueInvalid.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_valueInvalid.setFont(font)
        self.label_valueInvalid.setObjectName(_fromUtf8("label_valueInvalid"))
        self.horizontalLayout_12.addWidget(self.label_valueInvalid)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_defaultValue = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_defaultValue.setFont(font)
        self.label_defaultValue.setObjectName(_fromUtf8("label_defaultValue"))
        self.horizontalLayout_13.addWidget(self.label_defaultValue)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.lineEdit_defaultValue = QtGui.QLineEdit(Dialog)
        self.lineEdit_defaultValue.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_defaultValue.setMaximumSize(QtCore.QSize(180, 180))
        self.lineEdit_defaultValue.setText(_fromUtf8(""))
        self.lineEdit_defaultValue.setObjectName(_fromUtf8("lineEdit_defaultValue"))
        self.horizontalLayout_13.addWidget(self.lineEdit_defaultValue)
        self.label_defaultValueInvalid = QtGui.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_defaultValueInvalid.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_defaultValueInvalid.setFont(font)
        self.label_defaultValueInvalid.setObjectName(_fromUtf8("label_defaultValueInvalid"))
        self.horizontalLayout_13.addWidget(self.label_defaultValueInvalid)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.buttonBox_OkCancel = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_OkCancel.sizePolicy().hasHeightForWidth())
        self.buttonBox_OkCancel.setSizePolicy(sizePolicy)
        self.buttonBox_OkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_OkCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_OkCancel.setObjectName(_fromUtf8("buttonBox_OkCancel"))
        self.verticalLayout.addWidget(self.buttonBox_OkCancel)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_OkCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_OkCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Add/Edit Sensor", None))
        self.label_systemType.setText(_translate("Dialog", "Sensor Category:", None))
        self.comboBox_systemType.setItemText(0, _translate("Dialog", "TSV", None))
        self.comboBox_systemType.setItemText(1, _translate("Dialog", "GLV", None))
        self.comboBox_systemType.setItemText(2, _translate("Dialog", "DYNO", None))
        self.label_sensorName_2.setText(_translate("Dialog", "Sensor Name:", None))
        self.label_canID.setText(_translate("Dialog", "CAN ID:", None))
        self.label_canIDInvalid.setText(_translate("Dialog", "X", None))
        self.label_canStartByte.setText(_translate("Dialog", "CAN Start Byte:", None))
        self.comboBox_canStartByte.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox_canStartByte.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox_canStartByte.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox_canStartByte.setItemText(3, _translate("Dialog", "4", None))
        self.comboBox_canStartByte.setItemText(4, _translate("Dialog", "5", None))
        self.comboBox_canStartByte.setItemText(5, _translate("Dialog", "6", None))
        self.comboBox_canStartByte.setItemText(6, _translate("Dialog", "7", None))
        self.comboBox_canStartByte.setItemText(7, _translate("Dialog", "8", None))
        self.label_canByteAmount.setText(_translate("Dialog", "CAN Data Length:", None))
        self.comboBox_canByteAmount.setItemText(0, _translate("Dialog", "1 bit", None))
        self.comboBox_canByteAmount.setItemText(1, _translate("Dialog", " 1 byte", None))
        self.comboBox_canByteAmount.setItemText(2, _translate("Dialog", "2 bytes", None))
        self.label.setText(_translate("Dialog", "CAN Bit Location:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "bit 1", None))
        self.comboBox.setItemText(1, _translate("Dialog", "bit 2", None))
        self.comboBox.setItemText(2, _translate("Dialog", "bit 3", None))
        self.comboBox.setItemText(3, _translate("Dialog", "bit 4", None))
        self.comboBox.setItemText(4, _translate("Dialog", "bit 5", None))
        self.comboBox.setItemText(5, _translate("Dialog", "bit 6", None))
        self.comboBox.setItemText(6, _translate("Dialog", "bit 7", None))
        self.comboBox.setItemText(7, _translate("Dialog", "bit 8", None))
        self.label_calibration.setText(_translate("Dialog", "Calibration Coefficients:", None))
        self.label_2.setText(_translate("Dialog", "F(x) = A*x^2 + B*x + C + D*(1/x) + E*(1/x^2)", None))
        self.label_square.setText(_translate("Dialog", "Square (A):", None))
        self.lineEdit_square.setText(_translate("Dialog", "0", None))
        self.label_linear.setText(_translate("Dialog", "Linear (B):", None))
        self.lineEdit_linear.setText(_translate("Dialog", "1", None))
        self.label_constant.setText(_translate("Dialog", "Constant (C):", None))
        self.lineEdit_constant.setText(_translate("Dialog", "0", None))
        self.label_inverse.setText(_translate("Dialog", "Inverse (D):", None))
        self.lineEdit_inverse.setText(_translate("Dialog", "0", None))
        self.label_inverseSquare.setText(_translate("Dialog", "Inverse Square (E):", None))
        self.lineEdit_inverseSquare.setText(_translate("Dialog", "0", None))
        self.label_sensorUnits.setText(_translate("Dialog", "Sensor Units:", None))
        self.comboBox_sensorUnits.setItemText(0, _translate("Dialog", "V", None))
        self.comboBox_sensorUnits.setItemText(1, _translate("Dialog", "A", None))
        self.comboBox_sensorUnits.setItemText(2, _translate("Dialog", "C", None))
        self.comboBox_sensorUnits.setItemText(3, _translate("Dialog", "%", None))
        self.label_sensorType.setText(_translate("Dialog", "Sensor Type:", None))
        self.comboBox_sensorType.setItemText(0, _translate("Dialog", "Analog Output", None))
        self.comboBox_sensorType.setItemText(1, _translate("Dialog", "Analog Input", None))
        self.comboBox_sensorType.setItemText(2, _translate("Dialog", "Digital Input", None))
        self.comboBox_sensorType.setItemText(3, _translate("Dialog", "Digital Output", None))
        self.label_samplingRate.setText(_translate("Dialog", "Sampling Rate (secs):", None))
        self.label_samplingRateInvalid.setText(_translate("Dialog", "X", None))
        self.label_overwritePeriod.setText(_translate("Dialog", "Graph Data Overwrite Period (hrs):", None))
        self.label_overwritePeriodInvalid.setText(_translate("Dialog", "X", None))
        self.label_value.setText(_translate("Dialog", "Value (current setting):", None))
        self.label_valueInvalid.setText(_translate("Dialog", "X", None))
        self.label_defaultValue.setText(_translate("Dialog", "Default Value (load at startup):", None))
        self.label_defaultValueInvalid.setText(_translate("Dialog", "X", None))

